
running 1 test
test test::test ... FAILED

failures:

---- test::test stdout ----
thread 'test::test' panicked at src/lib.rs:37:50:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test::test

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

